rules:
  default: true
  custom:
    - seriesQuery: 'container_memory_usage_bytes{namespace!="",container!=""}'
      resources:
        overrides:
          namespace: {resource: "namespace"}
          pod: {resource: "pod"}
      name:
        matches: "^(.*)_total"
        as: "${1}"
      metricsQuery: 'avg(rate(container_memory_usage_bytes[2m])) by (namespace, pod)'
