apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: dhbw-tube
build:
  artifacts:
    - image: dhbw-tube-frontend
      context: dhbw-tube-frontend
      docker:
        dockerfile: Dockerfile
    - image: dhbw-tube-stream
      context: dhbw-tube-stream
      docker:
        dockerfile: Dockerfile
    - image: dhbw-tube-upload
      context: dhbw-tube-upload
      docker:
        dockerfile: Dockerfile
    - image: minio
      context: minio
      docker:
        dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      # Apply namespace
      - k8s/namespace.yaml

      # Apply secrets
      - k8s/secrets/postgres-secret.yaml
      - k8s/secrets/minio-secret.yaml
      - k8s/secrets/grafana-secret.yaml

      # Apply persistent volume claims
      - k8s/postgres/postgres-pvc.yaml
      - k8s/minio/minio-pvc.yaml
      - k8s/prometheus/prometheus-pv.yaml
      - k8s/prometheus/prometheus-pvc.yaml
      - k8s/grafana/grafana-pv.yaml
      - k8s/grafana/grafana-pvc.yaml

      # Apply config maps
      - k8s/postgres/postgres-config-map.yaml
      - k8s/upload/upload-config-map.yaml
      - k8s/stream/stream-config-map.yaml
      - k8s/frontend/frontend-config-map.yaml

      # Apply stateful sets
      - k8s/postgres/postgres-stateful-set.yaml
      - k8s/minio/minio-stateful-set.yaml

      # Apply deployments
      - k8s/memcached/memcached-deployment.yaml
      - k8s/upload/upload-deployment.yaml
      - k8s/stream/stream-deployment.yaml
      - k8s/frontend/frontend-deployment.yaml

      # Apply services
      - k8s/postgres/postgres-service.yaml
      - k8s/minio/minio-service.yaml
      - k8s/memcached/memcached-service.yaml
      - k8s/upload/upload-service.yaml
      - k8s/stream/stream-service.yaml
      - k8s/frontend/frontend-service.yaml

      # Apply metrics server for autoscaling
      - https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml

      # Apply horizontal pod autoscalers
      - k8s/upload/upload-hpa.yaml
      - k8s/stream/stream-hpa.yaml
      - k8s/frontend/frontend-hpa.yaml

      # Apply vertical pod autoscalers
      - k8s/postgres/postgres-vpa.yaml
      - k8s/minio/minio-vpa.yaml