apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: dhbw-tube
build:
  artifacts:
    - image: dhbw-tube-frontend
      context: dhbw-tube-frontend
      docker:
        dockerfile: Dockerfile
    - image: dhbw-tube-stream
      context: dhbw-tube-stream
      docker:
        dockerfile: Dockerfile
    - image: dhbw-tube-upload
      context: dhbw-tube-upload
      docker:
        dockerfile: Dockerfile
    - image: minio
      context: minio
      docker:
        dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      # Apply namespace
      - k8s/namespace.yaml

      # Apply persistent volume claims
      - k8s/postgres/postgres-pvc.yaml
      - k8s/minio/minio-pvc.yaml

      # Apply config maps
      - k8s/postgres/postgres-config-map.yaml
      - k8s/minio/minio-config-map.yaml
      - k8s/upload/upload-config-map.yaml
      - k8s/stream/stream-config-map.yaml
      - k8s/frontend/frontend-config-map.yaml

      # Apply deployments
      - k8s/postgres/postgres-deployment.yaml
      - k8s/minio/minio-deployment.yaml
      - k8s/memcached/memcached-deployment.yaml
      - k8s/upload/upload-deployment.yaml
      - k8s/stream/stream-deployment.yaml
      - k8s/frontend/frontend-deployment.yaml

      # Apply services
      - k8s/postgres/postgres-service.yaml
      - k8s/minio/minio-service.yaml
      - k8s/memcached/memcached-service.yaml
      - k8s/upload/upload-service.yaml
      - k8s/stream/stream-service.yaml
      - k8s/frontend/frontend-service.yaml
#  helm:
#    releases:
#      - name: prometheus
#        chartPath: prometheus-community/prometheus
#        namespace: dhbw-tube
#        setValues:
#          service:
#            type: NodePort
#            nodePort: 8888
#          server:
#            global:
#              scrape_interval: 15s
#        wait: true
#      - name: grafana
#        chartPath: grafana/grafana
#        namespace: dhbw-tube
#        setValues:
#          service:
#            type: NodePort
#            nodePort: 99990
#          adminPassword: "admin"
#        wait: true