apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: dhbw-tube
type: Opaque
data:
  admin-user: YWRtaW4=        # Base64 für "admin"
  admin-password: YWRtaW4=    # Base64 für "passwort"