apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config-map
  namespace: dhbw-tube
data:
  UPLOAD_BASE_URL: "http://upload-service.dhbw-tube.svc.cluster.local"
  STREAM_BASE_URL: "http://stream-service.dhbw-tube.svc.cluster.local"