apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config-map
  namespace: dhbw-tube
data:
  nginx.conf: |
    server {
        listen 80;
    
        root /usr/share/nginx/html;
        index index.html;
    
        # Host static files
        location / {
            try_files $uri $uri/ /index.html;
        }
    
        # proxy configuration for the upload service
        location /upload-api {
            proxy_pass http://localhost/upload-api;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    
        # proxy configuration for the stream service
        location /stream-api {
            proxy_pass http://localhost/stream-api;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location ~* \.(jpg|jpeg|png|gif|ico|css|js)$ {
            expires 1y;
            log_not_found off;
        }
    }