# Define default.conf for nginx server. The REST-API calls will be redirected to the corresponding services.
# The maximum file size for uploads is set to 5GB, so the user can upload a 4GB video + metadata & 10MB cover image.
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config-map
  namespace: dhbw-tube
data:
  default.conf: |
    server {
        listen 80;

        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
            try_files $uri $uri/ /index.html;
        }

        location /upload-api/ {
            client_max_body_size 5G;
            proxy_pass http://upload-service:5000/;
            proxy_set_header Host $host;
            add_header Access-Control-Allow-Origin *;
            add_header Access-Control-Allow-Methods 'GET, POST, OPTIONS';
            add_header Access-Control-Allow-Headers 'Content-Type, Authorization';
        }

        location /stream-api/ {
            proxy_pass http://stream-service:5001/;
            proxy_set_header Host $host;
            add_header Access-Control-Allow-Origin *;
            add_header Access-Control-Allow-Methods 'GET, POST, OPTIONS';
            add_header Access-Control-Allow-Headers 'Content-Type, Authorization';
        }
    }
