apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: dhbw-tube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "80"
    spec:
      # Frontend depends on upload and stream. Therefore, we need to wait for them to be ready using init containers.
      initContainers:
        - name: wait-for-upload
          image: busybox
          command: [ 'sh', '-c', 'until nc -z upload-service 5000; do echo waiting for upload; sleep 5; done;' ]
        - name: wait-for-stream
          image: busybox
          command: [ 'sh', '-c', 'until nc -z stream-service 5001; do echo waiting for stream; sleep 5; done;' ]

      containers:
        - name: frontend
          image: dhbw-tube-frontend
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: nginx-config-volume
          configMap:
            name: frontend-config-map