apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: minio-vpa
  namespace: dhbw-tube
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: minio-stateful-set
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
      - containerName: minio
        minAllowed:         # Set the value slightly below the initial requests to avoid undersizing but still allow flexibility.
          cpu: "250m"
          memory: "500Mi"
        maxAllowed:
          cpu: "750m"
          memory: "7Gi"