apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: dhbw-tube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio
          imagePullPolicy: Never
          args:
            - server
            - /data
          envFrom:
            - configMapRef:
                name: minio-config
          ports:
            - containerPort: 9000
            - containerPort: 9001
          volumeMounts:
            - name: minio-data
              mountPath: /data
          livenessProbe:
            exec:
              command: [ "/usr/local/bin/check-health.sh" ]
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 10
          readinessProbe:
            exec:
              command: [ "/usr/local/bin/check-health.sh" ]
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 10
      volumes:
        - name: minio-data
          persistentVolumeClaim:
            claimName: minio-pvc