apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: dhbw-tube
spec:
  selector:
    app: minio-app
  ports:
    - name: admin-console
      protocol: TCP
      port: 9000
      targetPort: 9000
    - name: gui
      protocol: TCP
      port: 9001
      targetPort: 9001