apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dhbw-tube-ingress
  namespace: dhbw-tube
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
          - path: /upload-api
            pathType: Prefix
            backend:
              service:
                name: upload-service
                port:
                  number: 5000
          - path: /stream-api
            pathType: Prefix
            backend:
              service:
                name: stream-service
                port:
                  number: 5000
