apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcached-deployment
  namespace: dhbw-tube
  labels:
    app: memcached-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memcached-app
  template:
    metadata:
      labels:
        app: memcached-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "11211"
    spec:
      containers:
        - name: memcached
          image: memcached:alpine
          ports:
            - containerPort: 11211
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          livenessProbe:
            tcpSocket:
              port: 11211
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 11211
            initialDelaySeconds: 5
            periodSeconds: 10