apiVersion: v1
kind: Service
metadata:
  name: upload-service
  namespace: dhbw-tube
spec:
  selector:
    app: upload-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5000