apiVersion: apps/v1
kind: Deployment
metadata:
  name: stream
  namespace: dhbw-tube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stream
  template:
    metadata:
      labels:
        app: stream
    spec:
      containers:
      - name: stream
        image: dhbw-tube-stream
        envFrom:
        - configMapRef:
            name: stream-config
        ports:
        - containerPort: 5000