apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: dhbw-tube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: dhbw-tube-frontend
        ports:
        - containerPort: 80