apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: dhbw-tube
spec:
  replicas: 1

  selector:
    matchLabels:
      app: postgres-app

  template:
    metadata:
      labels:
        app: postgres-app

    spec:
      containers:
        - name: postgres
          image: postgres
          envFrom:
            - configMapRef:
                name: postgres-config-map
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data

          # Define liveness and readiness probes so services that depend on the database can check if the database is ready.
          livenessProbe:
            exec:
              command: [ "pg_isready", "-U", "postgres" ]
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 10
          readinessProbe:
            exec:
              command: [ "pg_isready", "-U", "postgres" ]
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 10

      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc