apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: dhbw-tube
spec:
  clusterIP: None
  selector:
    app: postgres-app
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432