apiVersion: v1
kind: Service
metadata:
  name: stream-service
  namespace: dhbw-tube
spec:
  selector:
    app: stream-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000