apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload
  namespace: dhbw-tube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upload
  template:
    metadata:
      labels:
        app: upload
    spec:
      containers:
      - name: upload
        image: dhbw-tube-upload
        envFrom:
        - configMapRef:
            name: upload-config
        ports:
        - containerPort: 5000