apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: dhbw-tube
type: Opaque
data:
  MINIO_ACCESS_KEY: bWluaW9hZG1pbg==  # base64 encoded 'minioadmin'
  MINIO_SECRET_KEY: bWluaW9hZG1pbg==  # base64 encoded 'minioadmin'